env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

plugins:
  - unused-imports

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.eslint.json

rules:
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
      newlines-between: always
  '@typescript-eslint/consistent-type-imports': error
  unused-imports/no-unused-imports: warn

settings:
  import/resolver: typescript
