env:
  node: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'

rules:
  import/order:
    - 2
    - alphabetize:
        order: 'asc'

settings:
  import/resolver:
    typescript: ''
