name: 'ci'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

			- uses: pnpm/action-setup@v2

    	- uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

			-	run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

			- uses: pnpm/action-setup@v2

    	- uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

			-	run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm run test:coverage --passWithNoTests

      - name: Upload coverage
        uses: codecov/codecov-action@v2
