name: 'lint'

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '>=16.6.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
