name: 'test'

on: pull_request

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Read node version from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.package-version.outputs.version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run test
        run: yarn test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v2
